### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This 

### ISSUE THREAD

**Issue by axk2** [alexislepresle/gatsby-plugin-paypal#1]
×
i have this error when i try to use this plugin

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

//component
`
import React from "react"
import Paypal from "gatsby-plugin-paypal"

const PaylpalButton = () => (
    <Paypal 
      style={{
        shape: 'rect',
        color: 'blue',
        layout: 'horizontal',
        label: 'paypal',
      }}
      amount={10.1}
    />
)

export default PaylpalButton
`

//just a simple page
`
import React from 'react'
import PaypalButton from '../components/PaypalButton'

const Home= () => {
    return (
            <PaypalButton />
    )
}

export default Home
`

//config
`
 ....
 plugins: [
    {
      resolve: `gatsby-plugin-paypal`,
      options: {
        clientId: process.env.PAYPAL_ID
      }
    },
....
]
....
`

plugin version 1.1

**Comment by alexislepresle** [comment]
Hello @axk2,
You should try it like this: 
```
import React from "react"
import Paypal from "gatsby-plugin-paypal"

const PaylpalButton = () => {   
   return (
      <Paypal
          style={{
              shape: 'rect',
              color: 'blue',
              layout: 'horizontal',
              label: 'paypal',
          }}
          amount={10.1}
      />
   )
}

export default PaylpalButton

**Comment by axk2** [comment]
![imagen_2021-01-21_203527](https://user-images.githubusercontent.com/71668489/105425615-54afbc00-5c0f-11eb-9bd2-2ac0de92757d.png)

![error](https://user-images.githubusercontent.com/71668489/105425641-6002e780-5c0f-11eb-9333-62d13ab2b9bd.png)

i have the same code, i use the documentation and i took my id from the link

**Comment by axk2** [comment]
![Code](https://user-images.githubusercontent.com/71668489/105425860-bec86100-5c0f-11eb-86ef-5732827d4d88.png)

**Comment by axk2** [comment]
![Code](https://user-images.githubusercontent.com/71668489/105425890-c7b93280-5c0f-11eb-92b8-9264eb0378ea.png)
![error](https://user-images.githubusercontent.com/71668489/105425893-c851c900-5c0f-11eb-81df-0fe9f7ba3d49.png)

i've just made all of the documentation, the id, the config, the install, the component, and always is the same error

**Comment by axk2** [comment]
i've deleted all the cache files, node modules, etc, installed all again

**Comment by alexislepresle** [comment]
Could you invite me to your repo? So that I can look at your code 👍🏻

**Comment by axk2** [comment]
sure, https://github.com/axk2/paypal-plugin-error i've replicated it for you, so it's simplier to analize

**Comment by alexislepresle** [comment]
Hello @axk2,

I just updated the packages and that's it, the issue is solved.

Thank you :)

**Comment by axk2** [comment]
thank you, it's a very good plugin, more people should use it

**Comment by yewyewxd** [comment]
@alexislepresle which packages did you update? I'm facing the same issue, would really appreciate it if you share more detail :)

**Comment by lawrenceberry** [comment]
Hi @alexislepresle, thanks for creating this package, it's really nifty! @yewyewXD I think this issue is still around and stems from the fact that the package is [specifying React as a dependency rather than just a peer dependency](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react). I was able to get around it by installing React 17 (`react@^17.0.1` and `react-dom@^17.0.1`) _before_ installing the plug-in. The package manager then successfully picked up the plug-in's React dependency as a duplicate. The ideal solution would be to remove React as a dependency of this package as the React docs suggest.

**Comment by alexislepresle** [comment]
Hi @lawjb , @yewyewXD ,

I just fixed the issue, normally it's good now :)
